config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :ideas
	root to: "ideas#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates  :name, presence:true
	validates :name, length: { minimum: 4 }
	has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
	belongs_to :category
	belongs_to :user
	validates  :name, presence: true
	has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :ideas
	include Gravtastic
  gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = current_user.ideas.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :content, :category_id, :user_id, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name,{},class:"form-control" %>
  </div>

    <%= hidden_field_tag 'idea[user_id]', current_user.id %>

  <!--<div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div> -->
<div class="input-group mt-5 mb-5">
  <div class="input-group-prepend">
    <span class="input-group-text" id="input_picture_upload">Picture Upload</span>
  </div>
  <div class="custom-file">
    <input type="file" class="custom-file-input" id="idea_picture"
      aria-describedby="input_picture_upload" name="idea[picture]">
    <label class="custom-file-label" for="idea_picture">Choose file</label>
  </div>
</div>


  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
<script>
$(function() {
	$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
});

</script>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Your Ideas</h1>

<% @ideas.in_groups_of(3).each do |group| %>
  <div class="row">
    <% group.compact.each do |idea| %>
      <div class="col-md-4">
        <%= image_tag idea.picture, width: '100%' if idea.picture.present? %>
        <h4 class="text-center"><%= link_to idea.name.upcase, idea %></h4>
        <%= idea.content %> <br />
				<%= idea.category.name %> 
      </div>
    <% end %>
  </div>
<% end %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<div class="row">
  <div class="col-md-9">
    <%= image_tag(@idea.picture, width: '100%') if @idea.picture.present? %>
  </div>

  <div class="col-md-3">
    <p class="text-center"><b>Name: </b><%= @idea.name %></p>
    <p><b>Description: </b><%= @idea.content %></p>
    <p>
      <%= link_to 'Edit', edit_idea_path(@idea), class:"btn btn-primary" %>
      <%= link_to 'Destroy', @idea, data: { confirm: 'Are you sure?' }, method: :delete, class:"btn btn-danger" %>
      <%= link_to 'Back', ideas_path, class:"btn btn-success" %>
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">The Idea app</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav pull-right">
			  <li class="nav-item"><a class="nav-link" href="<%= ideas_path %>">Ideas</a></li>
				<li class="nav-item"><%= link_to 'New Idea', new_idea_path, class: "nav-link" %></li>
			
			<% if user_signed_in? %>
				<li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
				<li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %> </li>
			<% else %>
				<li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
				<li class="nav-item"><%= link_to "Log In", new_user_session_path, class: "nav-link" %></li>
			<% end %>
    </ul>
		<% if user_signed_in? %>
			<span class="navbar-text">
				Logged in as <strong><%= current_user.email %>
			</span>		
		<% end %>

  </div>
</nav>

app/views/layouts/_header2.html.erb
<!--Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark" style="background:green;">
  <a class="navbar-brand" href="#">The Ideas App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
    aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
    <ul class="navbar-nav mr-auto">
			  <li class="nav-item"><a class="nav-link" href="<%= ideas_path %>">Ideas</a></li>
				<li class="nav-item"><%= link_to 'New Idea', new_idea_path, class: "nav-link" %></li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
			<% if user_signed_in? %>
				<li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
				<li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %> </li>
			<li class="nav-item"><a class="nav-link">
          <img src="<%=current_user.gravatar_url%>" style="width:30px"class="rounded-circle z-depth-0"
            alt="avatar image">
        </a> </li>
			<% else %>
				<li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
				<li class="nav-item"><%= link_to "Log In", new_user_session_path, class: "nav-link" %></li>
			<% end %>
    </ul>
  </div>
</nav>
<!--/.Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeasApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		
		  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
		body{
			width:80%;
			margin:auto;
		}
				.jumbotron{
			background:green;
			color:white;
		}
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
		
		
  </head>

  <body>
	<%= render partial: 'layouts/header2' %>	
		
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
		

	
		
    
<div class="container">
  <%= yield %>
</div>
		

		
		
<footer>
  <div class="container">
    Ruby Training <%= Time.now.year %>
  </div>
</footer>
<script>
	$(document).ready(function(){

		$(".nav>li").each(function() {
    var navItem = $(this);
    if (navItem.find("a").attr("href") == location.pathname) {
      navItem.addClass("active");
    }
});

});
	
		</script>
		
		
		
  </body>
</html>